oppgavestyring:
  host: http://oppgavestyring
  audience: dev-gcp:aap:oppgavestyring
  scope: api://dev-gcp.aap.oppgavestyring/.default
  testbruker-passord: ${TESTBRUKERE_PASSORD}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}

kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}

dolly:
  url: https://dolly-backend.dev.intern.nav.no/api/v1
  scope: api://cf878fa5-aa6b-4bc5-bb2e-40b27e6c0149/.default
