name: Deploy Bot

on:
  push:
    branches: [ main ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: 19
          distribution: 'zulu'

      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: test app:buildFatJar --continue --no-daemon --configuration-cache

      - uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: test
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build --pull --tag ${{ env.IMAGE }} --tag ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }} --all-tags

  deploy:
    concurrency:
      group: deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yml
