name: Deploy Bot

on:
  push:
    branches: [ main ]

env:
  IMAGE: ${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      checks: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.10.0
        with:
          java-version: 19
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: test app:buildFatJar --continue --no-daemon --configuration-cache

      - uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: test
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ env.IMAGE }}

      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
